# Generated by Django 4.1.5 on 2023-06-13 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stadium', '0001_stadium_models_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stadiums', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
